### ISSUE TITLE
테스트를 풀리퀘를 해주신다면 정말 감사할 것 같습니다.

### ISSUE THREAD

**Issue by indongyoo** [Functional-JavaScript/functional.es#3]
어떤 분께서 동기/비동기를 테스트 할 수 있는 테스트를 작성해주신다면 정말 감사할 것 같습니다.

마수걸이를 해주시면 저도 해당 파일에 여러 테스트도 올리도록 하겠습니다.

감사합니다.

**Comment by adhrinae** [comment]
현재 저장소 구조에서 테스트 코드를 작성하고 실행하고자 한다면 두가지 옵션이 있어 보입니다.

1. QUnit으로 브라우저에서 테스트를 한다. CDN에서 QUnit을 불러오는 `index.html` 파일 생성. 그리고 `index.html` 파일에서 `tests.js` 파일을 불러온다. 결과는 브라우저에 자동으로 표시됨
2. 폴더를 분리하던지 하여 mocha + chai가 불러와진 npm repository를 설정하고 functional.es.js의 다양한 함수들을 테스트한다. 다 설정되고 나면 `npm test` 등의 스크립트로 바로 결과물 확인

개인적으로 테스트를 작성하고자 한다면 2번이 낫다고 생각합니다.

**Comment by indongyoo** [comment]
앗 여기서도 뵙네요. 방갑습니다. 2번이 뭔가 더 멋진거 같긴한데요. 
1번으로 가볍게 가도 될거 같은데 어떨까요?

FunctionalES외에도 앞으로 브라우저용 코드들도 많이 작성할거 같은데, 
같은 방식으로 운영되면 좋을거 같습니다.
