### ISSUE TITLE
빠진 부분이 있는 것 같은데 확인 부탁드립니다.

### ISSUE THREAD

**Issue by soomtong** [Functional-JavaScript/functional.es#6]
좋은 강의 감사합니다.

컨커런시 부분에서 아래 내용 중 

## 병렬적으로 동작할 수 없는 async/await

async/await는 병렬적으로 일어나는 일을 처리하지 못합니다. 하나씩 순차적으로 기다리는 경우에만 사용할 수 있습니다. 동시성 프로그래밍을 하기 위해서는 헬퍼 함수가 반드시 필요합니다.

```javascript
// 동시에 users와 posts 출발
const res1 = awiat concurrency({
  users: _=> query(...),
  posts: _=> query(...)
});
//{
//  users: [row, row, row, ...]
//  posts: [row, row, row, ...]
//}

// await를 만날 때마다 하나씩 출발
const res2 = {
  users: await query(...),
  posts: await query(...)
}
//{
//  users: [row, row, row, ...]
//  posts: [row, row, row, ...]
//}
```

두 번째 코드 중

```javascript
const res2 = 무엇 {
// ...
}
```

저 무엇에 해당하는 series 나 concurrency 같은 함수가 있어야 하는 것 같습니다.

**Comment by indongyoo** [comment]
전자와 후자가 차이가 있다는 것을 설명하기 위해 (await만을 사용했을 때는 순차적으로만 실행이 된다는 점을 설명하고자) 적은 예제입니다. 그대로 두도록 하겠습니다. 감사합니다 :)

**Comment by soomtong** [comment]
코드가 맞다는 것을 인식하고 다시 보니 이해가 되었습니다. 감사합니다!

**Comment by indongyoo** [comment]
넵. 흐름상 헷갈리는 부분이 있는거 같습니다. 나중에 잘 정리해보겠습니다. 감사합니다!
